export type Language = "pt" | "en";

export const profile = {
  email: "heitorbsouza20@gmail.com",
  github: "https://github.com/heitor-barbosa/",
  linkedin: "https://www.linkedin.com/in/heitor-barbosa-souza/",
  resume: `${import.meta.env.BASE_URL}curriculo-heitor-barbosa.pdf`,
};

export const content = {
  pt: {
    nav: ["Sobre", "Projetos", "Experiência", "Contato"],
    skip: "Pular para o conteúdo",
    menu: "Abrir menu",
    closeMenu: "Fechar menu",
    theme: "Ativar tema claro",
    themeDark: "Ativar tema escuro",
    eyebrow: "ENGENHARIA DE SOFTWARE & CURIOSIDADE",
    hello: "Olá, eu sou o Heitor",
    title: ["Código que resolve.", "Software que", "faz a diferença."],
    intro:
      "Desenvolvedor full stack. Transformo problemas complexos em sistemas eficientes — do backend à experiência de quem usa.",
    projectsCta: "Explore meus projetos",
    resume: "Baixar currículo",
    resumeLang: "Currículo em português (PDF)",
    location: "Goiânia, Brasil",
    scroll: "Continue explorando",
    visualTop: "IDEIAS → SISTEMAS",
    visualBottom: "CONSTRUÍDO COM PROPÓSITO",
    visualLabels: ["Interfaces", "Sistemas", "Inteligência"],
    aboutLabel: "01 / SOBRE MIM",
    aboutTitle: "Entre a lógica",
    aboutAccent: "e a possibilidade.",
    aboutText:
      "Gosto de entender como as coisas funcionam. E de encontrar uma forma melhor de fazê-las funcionar.",
    aboutBody:
      "Sou desenvolvedor backend na One Conciliadora e estudante de Engenharia de Software na UFG. Construo aplicações full stack, automatizo processos e exploro como agentes de IA podem transformar o desenvolvimento de software no CEIA/UFG.",
    education: "Engenharia de Software",
    university: "Universidade Federal de Goiás",
    educationDate: "2024 — atual",
    languages: "Português nativo · Inglês fluente",
    stackLabel: "MINHA CAIXA DE FERRAMENTAS",
    projectLabel: "02 / PROJETOS SELECIONADOS",
    projectTitle: "Problemas reais.",
    projectAccent: "Impacto concreto.",
    projectIntro: "Uma seleção do que venho construindo na prática.",
    projectMore: "Sobre o projeto",
    projectPrivate: "Projeto profissional · código privado",
    concept: "Representação visual do projeto",
    projects: [
      {
        title: "Conciliação, sem complicação.",
        category: "BACKEND · AUTOMAÇÃO",
        company: "ONE CONCILIADORA",
        description:
          "Uma plataforma financeira que conecta vendas, pagamentos e extratos. Menos planilhas. Mais clareza.",
        tags: ["Python", "Django", "PostgreSQL", "Pandas"],
        metric: "170",
        metricLabel: "clientes atendidos",
        detail:
          "Co-desenvolvi do zero uma plataforma de conciliação financeira em produção. Implementei importadores de arquivos .xlsx, .csv, .ofx e .bbt com validações de estrutura, período, CNPJ, NSU e duplicidade, persistência em lote e transações atômicas.",
        results: [
          "Conferência de vendas reduzida de várias horas para cerca de 1 minuto.",
          "Coleta e importação diária no portal SiTef automatizada para 90 clientes com Playwright, Django Q e Redis.",
          "Consultas e paginação otimizadas: tela crítica de mais de 30 para aproximadamente 3 segundos.",
        ],
      },
      {
        title: "Uma operação mais conectada.",
        category: "FULL STACK · PRODUTO",
        company: "ONE CONCILIADORA",
        description:
          "Da negociação à implantação: um sistema interno para dar visibilidade a cada etapa da operação.",
        tags: ["React", "TypeScript", "Django REST", "PostgreSQL"],
        metric: "20",
        metricLabel: "usuários internos",
        detail:
          "Projetei e desenvolvi integralmente um sistema interno full stack para gerenciar negociações, contratos, implantações, operações e tarefas dos clientes da empresa.",
        results: [
          "Utilizado por 20 usuários na gestão de uma carteira de 170 clientes.",
          "Frontend em React e TypeScript integrado a uma API em Django REST Framework.",
          "Persistência em PostgreSQL e organização dos processos em uma única aplicação.",
        ],
      },
      {
        title: "A próxima forma de construir.",
        category: "INTELIGÊNCIA ARTIFICIAL · P&D",
        company: "CEIA / UFG",
        description:
          "Agentes de IA e especificações executáveis para explorar novos caminhos na engenharia de software.",
        tags: ["LLMs", "AI Agents", "SDD"],
        metric: "AI4SE",
        metricLabel: "pesquisa em andamento",
        detail:
          "Integro a Frente 1 do projeto de P&D AI4SE, no Centro de Excelência em Inteligência Artificial da UFG, desde agosto de 2026. O projeto investiga IA Generativa Autônoma para Engenharia de Software.",
        results: [
          "Pesquisa e desenvolvimento com agentes de IA baseados em modelos de linguagem.",
          "Participação no framework de agentes com Spec-Driven Development (SDD).",
          "Foco em especificações executáveis e versionáveis e orquestração entre fases do ciclo de vida do software.",
        ],
      },
    ],
    detailHeading: "O QUE EU CONSTRUÍ",
    resultsHeading: "NA PRÁTICA",
    close: "Fechar detalhes",
    experienceLabel: "03 / TRAJETÓRIA",
    experienceTitle: "Sempre em",
    experienceAccent: "construção.",
    experienceIntro: "Aprender, colocar em prática e seguir evoluindo.",
    present: "ATUAL",
    jobs: [
      {
        company: "CEIA / UFG",
        role: "Integrante de P&D · AI4SE",
        date: "AGO 2026 — ATUAL",
        text: "Pesquisa em agentes de IA, LLMs e Spec-Driven Development para engenharia de software.",
        type: "PESQUISA",
        current: true,
      },
      {
        company: "One Conciliadora",
        role: "Desenvolvedor Backend",
        date: "AGO 2025 — ATUAL",
        text: "Sistemas financeiros em produção, desenvolvimento full stack e automação de processos de ponta a ponta.",
        type: "DESENVOLVIMENTO",
        current: true,
      },
      {
        company: "ADS Marketing e Desenvolvimento",
        role: "Estagiário de Desenvolvimento",
        date: "JUN 2025 — AGO 2025",
        text: "Landing pages, e-commerce, APIs REST e dashboards de marketing integrados às APIs do Google.",
        type: "DESENVOLVIMENTO",
        current: false,
      },
    ],
    githubTitle: "Um commit de cada vez.",
    githubText:
      "Ideias, experimentos e aprendizado contínuo. Meu trabalho também acontece por aqui.",
    githubCta: "Explorar GitHub",
    githubReserved: "Meu próximo capítulo, em commits.",
    githubPlaceholder:
      "Espaço reservado para meu histórico de contribuições do GitHub.",
    githubBadge: "INTEGRAÇÃO EM BREVE",
    githubContributions: "contribuições",
    githubNote:
      "O gráfico será exibido aqui quando a integração estiver conectada.",
    contactLabel: "04 / VAMOS CONVERSAR",
    contactTitle: "Boas ideias merecem",
    contactAccent: "sair do papel.",
    contactText:
      "Tem um projeto em mente ou quer trocar uma ideia sobre tecnologia? Minha caixa de entrada está aberta.",
    emailCta: "Me mande um e-mail",
    copy: "Copiar e-mail",
    copied: "E-mail copiado!",
    copyFailed: "Não foi possível copiar. Use o link de e-mail.",
    footer: "Feito com React, café e intenção.",
    backTop: "Voltar ao topo",
    dashboard: {
      title: "Visão geral",
      subtitle: "Conciliação financeira",
      reconciled: "Conciliação",
      processing: "Processamento",
      active: "Em produção",
      clients: "Clientes",
      import: "Importar",
      checked: "Validar",
      done: "Conciliar",
    },
    workflow: ["Negociação", "Contrato", "Implantação", "Operação"],
    ai: ["Especificar", "Orquestrar", "Construir", "Validar"],
  },
  en: {
    nav: ["About", "Projects", "Experience", "Contact"],
    skip: "Skip to content",
    menu: "Open menu",
    closeMenu: "Close menu",
    theme: "Switch to light theme",
    themeDark: "Switch to dark theme",
    eyebrow: "SOFTWARE ENGINEERING & CURIOSITY",
    hello: "Hi, I’m Heitor",
    title: ["Code that solves.", "Software that", "makes a difference."],
    intro:
      "Full stack developer. I turn complex problems into efficient systems — from the backend to the experience of the people who use them.",
    projectsCta: "Explore my projects",
    resume: "Download résumé",
    resumeLang: "Résumé in Portuguese (PDF)",
    location: "Goiânia, Brazil",
    scroll: "Keep exploring",
    visualTop: "IDEAS → SYSTEMS",
    visualBottom: "BUILT WITH PURPOSE",
    visualLabels: ["Interfaces", "Systems", "Intelligence"],
    aboutLabel: "01 / ABOUT ME",
    aboutTitle: "Between logic",
    aboutAccent: "and possibility.",
    aboutText:
      "I like understanding how things work. And finding a better way to make them work.",
    aboutBody:
      "I’m a backend developer at One Conciliadora and a Software Engineering student at UFG. I build full stack applications, automate processes, and explore how AI agents can transform software development at CEIA/UFG.",
    education: "BSc in Software Engineering",
    university: "Federal University of Goiás",
    educationDate: "2024 — present",
    languages: "Native Portuguese · Fluent English",
    stackLabel: "MY TOOLBOX",
    projectLabel: "02 / SELECTED PROJECTS",
    projectTitle: "Real problems.",
    projectAccent: "Tangible impact.",
    projectIntro: "A selection of what I’ve been building.",
    projectMore: "About the project",
    projectPrivate: "Professional project · private source code",
    concept: "Conceptual project illustration",
    projects: [
      {
        title: "Reconciliation, simplified.",
        category: "BACKEND · AUTOMATION",
        company: "ONE CONCILIADORA",
        description:
          "A financial platform that connects sales, payments, and bank statements. Fewer spreadsheets. More clarity.",
        tags: ["Python", "Django", "PostgreSQL", "Pandas"],
        metric: "170",
        metricLabel: "clients served",
        detail:
          "I co-developed a production financial reconciliation platform from scratch. I implemented importers for .xlsx, .csv, .ofx, and .bbt files with structure, period, tax ID, transaction ID, and duplicate validation, plus bulk persistence and atomic transactions.",
        results: [
          "Sales verification reduced from several hours to about 1 minute.",
          "Daily collection and import from the SiTef portal automated for 90 clients with Playwright, Django Q, and Redis.",
          "Optimized queries and pagination: a critical screen reduced from over 30 to approximately 3 seconds.",
        ],
      },
      {
        title: "A more connected operation.",
        category: "FULL STACK · PRODUCT",
        company: "ONE CONCILIADORA",
        description:
          "From negotiation to onboarding: an internal system that brings visibility to every stage of operations.",
        tags: ["React", "TypeScript", "Django REST", "PostgreSQL"],
        metric: "20",
        metricLabel: "internal users",
        detail:
          "I designed and built an entire internal full stack system to manage negotiations, contracts, onboarding, operations, and tasks for the company’s clients.",
        results: [
          "Used by 20 team members to manage a portfolio of 170 clients.",
          "React and TypeScript frontend connected to a Django REST Framework API.",
          "PostgreSQL persistence and operational processes organized in a single application.",
        ],
      },
      {
        title: "The next way to build.",
        category: "ARTIFICIAL INTELLIGENCE · R&D",
        company: "CEIA / UFG",
        description:
          "AI agents and executable specifications to explore new paths in software engineering.",
        tags: ["LLMs", "AI Agents", "SDD"],
        metric: "AI4SE",
        metricLabel: "ongoing research",
        detail:
          "Since August 2026, I have been part of Workstream 1 of the AI4SE R&D project at UFG’s Center of Excellence in Artificial Intelligence. The project investigates Autonomous Generative AI for Software Engineering.",
        results: [
          "Research and development with AI agents powered by large language models.",
          "Contributing to an agent framework using Spec-Driven Development (SDD).",
          "Focus on executable, versioned specifications and orchestration across the software lifecycle.",
        ],
      },
    ],
    detailHeading: "WHAT I BUILT",
    resultsHeading: "IN PRACTICE",
    close: "Close details",
    experienceLabel: "03 / MY JOURNEY",
    experienceTitle: "Always",
    experienceAccent: "building.",
    experienceIntro: "Learning, putting it into practice, and moving forward.",
    present: "CURRENT",
    jobs: [
      {
        company: "CEIA / UFG",
        role: "R&D Project Member · AI4SE",
        date: "AUG 2026 — PRESENT",
        text: "Research into AI agents, LLMs, and Spec-Driven Development for software engineering.",
        type: "RESEARCH",
        current: true,
      },
      {
        company: "One Conciliadora",
        role: "Backend Developer",
        date: "AUG 2025 — PRESENT",
        text: "Production financial systems, full stack development, and end-to-end process automation.",
        type: "DEVELOPMENT",
        current: true,
      },
      {
        company: "ADS Marketing e Desenvolvimento",
        role: "Development Intern",
        date: "JUN 2025 — AUG 2025",
        text: "Landing pages, e-commerce, REST APIs, and marketing dashboards integrated with Google APIs.",
        type: "DEVELOPMENT",
        current: false,
      },
    ],
    githubTitle: "One commit at a time.",
    githubText:
      "Ideas, experiments, and continuous learning. My work happens here, too.",
    githubCta: "Explore GitHub",
    githubReserved: "My next chapter, in commits.",
    githubPlaceholder: "A space reserved for my GitHub contribution history.",
    githubBadge: "INTEGRATION COMING SOON",
    githubContributions: "contributions",
    githubNote: "The graph will appear here once the integration is connected.",
    contactLabel: "04 / LET’S TALK",
    contactTitle: "Good ideas deserve",
    contactAccent: "to become real.",
    contactText:
      "Have a project in mind or want to talk about technology? My inbox is open.",
    emailCta: "Send me an email",
    copy: "Copy email",
    copied: "Email copied!",
    copyFailed: "Could not copy. Please use the email link.",
    footer: "Made with React, coffee, and intention.",
    backTop: "Back to top",
    dashboard: {
      title: "Overview",
      subtitle: "Financial reconciliation",
      reconciled: "Reconciliation",
      processing: "Processing",
      active: "In production",
      clients: "Clients",
      import: "Import",
      checked: "Validate",
      done: "Reconcile",
    },
    workflow: ["Negotiation", "Contract", "Onboarding", "Operations"],
    ai: ["Specify", "Orchestrate", "Build", "Validate"],
  },
};

export type Copy = typeof content.pt;
